name: Crawl Inventory

on:
  schedule:
    - cron: "0 */4 * * *"   # 4時間おき
  workflow_dispatch:        # 手動実行ボタン
  push:
    paths:
      - "crawler.py"
      - "gspread_client.py"
      - "requirements.txt"
      - ".github/workflows/crawl.yml"

permissions:
  contents: write   # state/ をコミットするため

jobs:
  crawl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      # どこか run の前後に一時追加してね
      - name: Slack webhook quick test
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          python - <<'PY'
          import os, requests, json
          url = os.environ.get("SLACK_WEBHOOK_URL", "")
          print("Has SLACK_WEBHOOK_URL:", bool(url))
          if not url:
              raise SystemExit("❌ Secret SLACK_WEBHOOK_URL が空です")
          r = requests.post(url, json={"text":"✅ Webhook 単独テスト from GitHub Actions"}, timeout=15)
          print("Slack status:", r.status_code)
          print("Slack body:", r.text[:300])
          if r.status_code != 200 or r.text.strip().lower() not in ("ok", ""):
              raise SystemExit("❌ Slack に弾かれてます")
          PY
      - name: Run crawler
        env:
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
          SHEET_NAME: Listings_Input          # シート名（必要なら変更）
          SHEET_INV: Inventory   
          LINE_CHANNEL_TOKEN: ${{ secrets.LINE_CHANNEL_TOKEN }}
          LINE_TO: ${{ secrets.LINE_TO }}
        run: |
          python crawler.py

      - name: Commit state if changed
        run: |
          if [ -n "$(git status --porcelain state/ 2>/dev/null)" ]; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add state/inventory_state.json
            git commit -m "chore(state): update inventory_state.json [skip ci]"
            git push
          else
            echo "No state change."
          fi
