name: Extractor Test
on:
  workflow_dispatch:
    inputs:
      urls:
        description: "改行区切りのテストURL（空なら TEST_URLS を使用）"
        required: false
        default: ""

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run extractor smoke test
        env:
          EXTRACTOR_DEBUG: "1"
        run: |
          if [ -n "${{ github.event.inputs.urls }}" ]; then
            printf '%s\n' "${{ github.event.inputs.urls }}" | xargs -n1 python test_extractors.py
          else
            python test_extractors.py
          fi
